import type { FeatureBreakdown, Gender, Profile, ProfileCategory } from "@twinzy/types";

export interface CelebritySeed {
  fullName: string;
  slug: string;
  category: ProfileCategory;
  gender: Gender;
  dateOfBirth: string;
  nationality: string;
  country: string;
  city: string;
  occupation: string;
  biography: string;
  heightCm: number | null;
  eyeColor: string;
  hairColor: string;
  ethnicityCategory: string;
  imageUrl: string;
  extraImages?: string[];
  tags: string[];
  instagramUrl?: string;
  xUrl?: string;
  popularityScore: number;
}

export const REAL_CELEBRITIES: CelebritySeed[] = [
  {
    fullName: "Leonardo DiCaprio",
    slug: "leonardo-dicaprio",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1974-11-11",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actor",
    biography: "Leonardo DiCaprio is an Academy Award-winning actor known for Titanic, Inception, and The Revenant.",
    heightCm: 183,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Leonardo_DiCaprio_Cannes_2019.jpg",
    tags: ["oscar", "hollywood", "blockbuster"],
    popularityScore: 98,
  },
  {
    fullName: "Brad Pitt",
    slug: "brad-pitt",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1963-12-18",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actor",
    biography: "Brad Pitt is a Hollywood legend starring in Fight Club, Ocean's Eleven, and Once Upon a Time in Hollywood.",
    heightCm: 180,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Brad_Pitt-69858.jpg",
    tags: ["hollywood", "producer", "icon"],
    popularityScore: 97,
  },
  {
    fullName: "Tom Hanks",
    slug: "tom-hanks",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1956-07-09",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actor",
    biography: "Tom Hanks is one of America's most beloved actors, known for Forrest Gump and Saving Private Ryan.",
    heightCm: 183,
    eyeColor: "Blue",
    hairColor: "Gray",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Tom_Hanks_TIFF_2019.jpg",
    tags: ["oscar", "everyman", "classic"],
    popularityScore: 96,
  },
  {
    fullName: "Ryan Gosling",
    slug: "ryan-gosling",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1980-11-12",
    nationality: "Canadian",
    country: "Canada",
    city: "Toronto",
    occupation: "Actor",
    biography: "Ryan Gosling rose to fame with The Notebook and La La Land, becoming a modern romantic lead.",
    heightCm: 184,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Ryan_Gosling_-_Pale_Blue_Dot.jpg",
    tags: ["romance", "indie", "hollywood"],
    popularityScore: 92,
  },
  {
    fullName: "Scarlett Johansson",
    slug: "scarlett-johansson",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1984-11-22",
    nationality: "American",
    country: "United States",
    city: "New York",
    occupation: "Actress",
    biography: "Scarlett Johansson is a global superstar known for Lost in Translation and the Marvel Cinematic Universe.",
    heightCm: 160,
    eyeColor: "Green",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Scarlett_Johansson-8588.jpg",
    tags: ["marvel", "hollywood", "action"],
    popularityScore: 95,
  },
  {
    fullName: "Emma Stone",
    slug: "emma-stone",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1988-11-06",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actress",
    biography: "Emma Stone won an Oscar for La La Land and charmed audiences in Easy A and The Favourite.",
    heightCm: 168,
    eyeColor: "Green",
    hairColor: "Red",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/Emma_Stone-2468.jpg",
    tags: ["oscar", "comedy", "hollywood"],
    popularityScore: 91,
  },
  {
    fullName: "Shah Rukh Khan",
    slug: "shah-rukh-khan",
    category: "actor_bollywood",
    gender: "male",
    dateOfBirth: "1965-11-02",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actor",
    biography: "Shah Rukh Khan is the King of Bollywood with a career spanning decades of blockbuster romance and drama.",
    heightCm: 173,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Shahrukh_Khan_graces_the_launch_of_the_new_Santro.jpg",
    tags: ["bollywood", "king khan", "romance"],
    popularityScore: 99,
  },
  {
    fullName: "Deepika Padukone",
    slug: "deepika-padukone",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1986-01-05",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actress",
    biography: "Deepika Padukone is one of India's highest-paid actresses and a global fashion icon.",
    heightCm: 174,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Deepika_Padukone_at_Chhapaak_promotions.jpg",
    tags: ["bollywood", "fashion", "global"],
    popularityScore: 94,
  },
  {
    fullName: "Adel Emam",
    slug: "adel-emam",
    category: "actor_egyptian",
    gender: "male",
    dateOfBirth: "1940-05-17",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actor",
    biography: "Adel Emam is Egypt's most celebrated actor, known as the Zaeem with decades of comedy and drama classics.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Gray",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Adel_Emam.jpg",
    tags: ["egyptian cinema", "comedy", "legend"],
    popularityScore: 97,
  },
  {
    fullName: "Ahmed Helmy",
    slug: "ahmed-helmy",
    category: "actor_egyptian",
    gender: "male",
    dateOfBirth: "1969-11-18",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actor",
    biography: "Ahmed Helmy is one of Egypt's top comedy actors, beloved for his expressive performances and wit.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Ahmed_Helmy.jpg",
    tags: ["egyptian comedy", "box office", "star"],
    popularityScore: 93,
  },
  {
    fullName: "Yousra",
    slug: "yousra",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1955-03-17",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actress",
    biography: "Yousra is an iconic Egyptian actress and singer with a legendary career in Arab cinema.",
    heightCm: 165,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Yousra.jpg",
    tags: ["egyptian cinema", "diva", "classic"],
    popularityScore: 92,
  },
  {
    fullName: "Kivanc Tatlitug",
    slug: "kivanc-tatlitug",
    category: "actor_turkish",
    gender: "male",
    dateOfBirth: "1983-12-27",
    nationality: "Turkish",
    country: "Turkey",
    city: "Istanbul",
    occupation: "Actor",
    biography: "Kivanc Tatlitug is a Turkish heartthrob famous for Kurt Seyit ve Sura and international dizi fame.",
    heightCm: 187,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0c/K%C4%B1van%C3%A7_Tatlıtu%C4%9F.jpg",
    tags: ["dizi", "turkish", "romance"],
    popularityScore: 90,
  },
  {
    fullName: "Gong Yoo",
    slug: "gong-yoo",
    category: "actor_korean",
    gender: "male",
    dateOfBirth: "1979-07-10",
    nationality: "Korean",
    country: "South Korea",
    city: "Seoul",
    occupation: "Actor",
    biography: "Gong Yoo became a global sensation with Train to Busan and the hit series Goblin.",
    heightCm: 184,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Gong_Yoo_2016.jpg",
    tags: ["kdrama", "hallyu", "goblin"],
    popularityScore: 94,
  },
  {
    fullName: "Song Hye-kyo",
    slug: "song-hye-kyo",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1981-11-22",
    nationality: "Korean",
    country: "South Korea",
    city: "Seoul",
    occupation: "Actress",
    biography: "Song Hye-kyo is a leading Korean actress known for Descendants of the Sun and global brand campaigns.",
    heightCm: 161,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/Song_Hye-kyo_2016.jpg",
    tags: ["kdrama", "beauty", "global"],
    popularityScore: 93,
  },
  {
    fullName: "Mohamed Salah",
    slug: "mohamed-salah",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1992-06-15",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Footballer",
    biography: "Mohamed Salah is Egypt's football king and a Liverpool legend, adored across the Arab world and Europe.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Mohamed_Salah_2018.jpg",
    tags: ["premier league", "egypt", "football"],
    popularityScore: 98,
  },
  {
    fullName: "Lionel Messi",
    slug: "lionel-messi",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1987-06-24",
    nationality: "Argentine",
    country: "Argentina",
    city: "Rosario",
    occupation: "Footballer",
    biography: "Lionel Messi is widely regarded as one of the greatest footballers of all time and a World Cup champion.",
    heightCm: 170,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Latino",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg",
    tags: ["world cup", "barcelona", "goat"],
    popularityScore: 99,
  },
  {
    fullName: "Cristiano Ronaldo",
    slug: "cristiano-ronaldo",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1985-02-05",
    nationality: "Portuguese",
    country: "Portugal",
    city: "Funchal",
    occupation: "Footballer",
    biography: "Cristiano Ronaldo is a global football icon with records across Manchester United, Real Madrid, and beyond.",
    heightCm: 187,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg",
    tags: ["real madrid", "portugal", "legend"],
    popularityScore: 99,
  },
  {
    fullName: "LeBron James",
    slug: "lebron-james",
    category: "athlete_basketball",
    gender: "male",
    dateOfBirth: "1984-12-30",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Basketball Player",
    biography: "LeBron James is an NBA superstar and four-time champion known as King James.",
    heightCm: 206,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/LeBron_James_Lakers.jpg",
    tags: ["nba", "lakers", "champion"],
    popularityScore: 97,
  },
  {
    fullName: "Serena Williams",
    slug: "serena-williams",
    category: "athlete_tennis",
    gender: "female",
    dateOfBirth: "1981-09-26",
    nationality: "American",
    country: "United States",
    city: "Palm Beach",
    occupation: "Tennis Player",
    biography: "Serena Williams dominated women's tennis with 23 Grand Slam singles titles.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Serena_Williams_at_2013_US_Open.jpg",
    tags: ["grand slam", "tennis", "legend"],
    popularityScore: 95,
  },
  {
    fullName: "Taylor Swift",
    slug: "taylor-swift",
    category: "singer",
    gender: "female",
    dateOfBirth: "1989-12-13",
    nationality: "American",
    country: "United States",
    city: "Nashville",
    occupation: "Singer",
    biography: "Taylor Swift is a record-breaking pop superstar known for storytelling and the Eras Tour.",
    heightCm: 180,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png",
    tags: ["pop", "eras tour", "songwriter"],
    popularityScore: 99,
  },
  {
    fullName: "Beyonce",
    slug: "beyonce",
    category: "singer",
    gender: "female",
    dateOfBirth: "1981-09-04",
    nationality: "American",
    country: "United States",
    city: "Houston",
    occupation: "Singer",
    biography: "Beyonce is a global music icon, performer, and cultural force behind Destiny's Child and solo stardom.",
    heightCm: 169,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png",
    tags: ["r&b", "queen bey", "performer"],
    popularityScore: 98,
  },
  {
    fullName: "Amr Diab",
    slug: "amr-diab",
    category: "singer",
    gender: "male",
    dateOfBirth: "1961-10-11",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Singer",
    biography: "Amr Diab is the father of Mediterranean music and Egypt's best-selling artist of all time.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Amr_Diab_2017.jpg",
    tags: ["arabic pop", "egypt", "tamally maak"],
    popularityScore: 96,
  },
  {
    fullName: "Nancy Ajram",
    slug: "nancy-ajram",
    category: "singer",
    gender: "female",
    dateOfBirth: "1983-05-16",
    nationality: "Lebanese",
    country: "Lebanon",
    city: "Beirut",
    occupation: "Singer",
    biography: "Nancy Ajram is one of the Arab world's biggest pop stars with hits spanning two decades.",
    heightCm: 168,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Nancy_Ajram.jpg",
    tags: ["arabic pop", "lebanon", "diva"],
    popularityScore: 94,
  },
  {
    fullName: "MrBeast",
    slug: "mrbeast",
    category: "influencer",
    gender: "male",
    dateOfBirth: "1998-05-07",
    nationality: "American",
    country: "United States",
    city: "Greenville",
    occupation: "YouTuber",
    biography: "MrBeast is the world's most subscribed individual YouTuber, famous for massive giveaways and stunts.",
    heightCm: 191,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/MrBeast_2023.jpg",
    tags: ["youtube", "viral", "philanthropy"],
    popularityScore: 96,
  },
  {
    fullName: "Khaby Lame",
    slug: "khaby-lame",
    category: "influencer",
    gender: "male",
    dateOfBirth: "2000-03-09",
    nationality: "Senegalese",
    country: "Italy",
    city: "Chivasso",
    occupation: "TikToker",
    biography: "Khaby Lame became the most-followed person on TikTok with his silent comedy reactions.",
    heightCm: 185,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/KhabyLame.jpg",
    tags: ["tiktok", "comedy", "viral"],
    popularityScore: 93,
  },
  {
    fullName: "Albert Einstein",
    slug: "albert-einstein",
    category: "historical",
    gender: "male",
    dateOfBirth: "1879-03-14",
    nationality: "German",
    country: "Germany",
    city: "Ulm",
    occupation: "Physicist",
    biography: "Albert Einstein developed the theory of relativity and became the most famous scientist in history.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Gray",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Albert_Einstein_Head.jpg",
    tags: ["physics", "genius", "history"],
    popularityScore: 99,
  },
  {
    fullName: "Cleopatra VII",
    slug: "cleopatra",
    category: "historical",
    gender: "female",
    dateOfBirth: "0069-01-01",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Alexandria",
    occupation: "Queen",
    biography: "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt and a timeless icon.",
    heightCm: null,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Kleopatra-VII.-Altes-Museum-Berlin1.jpg",
    tags: ["ancient egypt", "queen", "history"],
    popularityScore: 95,
  },
  {
    fullName: "Chris Hemsworth",
    slug: "chris-hemsworth",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1983-08-11",
    nationality: "Australian",
    country: "Australia",
    city: "Melbourne",
    occupation: "Actor",
    biography: "Chris Hemsworth plays Thor in the Marvel Cinematic Universe and is known for his action roles.",
    heightCm: 190,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Chris_Hemsworth_by_Gage_Skidmore.jpg",
    tags: ["marvel", "thor", "action"],
    popularityScore: 93,
  },
  {
    fullName: "Zendaya",
    slug: "zendaya",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1996-09-01",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actress",
    biography: "Zendaya is an Emmy-winning actress and fashion icon starring in Euphoria and Spider-Man.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/28/Zendaya_-_2019_by_Glenn_Francis.jpg",
    tags: ["euphoria", "fashion", "spider-man"],
    popularityScore: 94,
  },
  {
    fullName: "Keanu Reeves",
    slug: "keanu-reeves",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1964-09-02",
    nationality: "Canadian",
    country: "Canada",
    city: "Toronto",
    occupation: "Actor",
    biography: "Keanu Reeves is beloved for The Matrix, John Wick, and his wholesome internet fame.",
    heightCm: 186,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Keanu_Reeves_%28crop_and_levels%29.jpg",
    tags: ["john wick", "matrix", "wholesome"],
    popularityScore: 96,
  },
];

export const FUNNY_OBJECT_SEEDS = [
  { name: "Potato", slug: "potato-funny", emoji: "🥔", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Patates.jpg", tags: ["starchy", "round", "comfort"] },
  { name: "Tomato", slug: "tomato-funny", emoji: "🍅", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg", tags: ["red", "juicy", "salad"] },
  { name: "Carrot", slug: "carrot-funny", emoji: "🥕", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/CarrotDiversityLg.jpg", tags: ["orange", "crunchy", "healthy"] },
  { name: "Onion", slug: "onion-funny", emoji: "🧅", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/25/Onion_on_White.JPG", tags: ["layered", "aromatic", "kitchen"] },
  { name: "Pumpkin", slug: "pumpkin-funny", emoji: "🎃", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Fairytale_pumpkin.jpg", tags: ["autumn", "round", "festive"] },
  { name: "Banana", slug: "banana-funny", emoji: "🍌", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg", tags: ["curved", "yellow", "tropical"] },
  { name: "Broccoli", slug: "broccoli-funny", emoji: "🥦", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Broccoli_and_cross_section_edit.jpg", tags: ["green", "tree", "healthy"] },
  { name: "Eggplant", slug: "eggplant-funny", emoji: "🍆", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Aubergine.jpg", tags: ["purple", "shiny", "veggie"] },
  { name: "Panda", slug: "panda-funny", emoji: "🐼", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Grosser_Panda.JPG", tags: ["fluffy", "bamboo", "cute"] },
  { name: "Cat", slug: "cat-funny", emoji: "🐱", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Cat_November_2010-1a.jpg", tags: ["whiskers", "sassy", "meme"] },
  { name: "Koala", slug: "koala-funny", emoji: "🐨", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Koala_climbing_tree.jpg", tags: ["sleepy", "fluffy", "australia"] },
  { name: "Duck", slug: "duck-funny", emoji: "🦆", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Peeking_duck.jpg", tags: ["quack", "waddle", "pond"] },
  { name: "Owl", slug: "owl-funny", emoji: "🦉", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Great_Horned_Owl_01.jpg", tags: ["wise", "night", "staring"] },
  { name: "Sloth", slug: "sloth-funny", emoji: "🦥", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/Bradypus.jpg", tags: ["slow", "chill", "hanging"] },
  { name: "Avocado", slug: "avocado-funny", emoji: "🥑", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/Avocado_fruit.jpg", tags: ["millennial", "green", "toast"] },
];

export function seededVector(seed: number, dimensions = 512): number[] {
  const vector: number[] = [];
  let state = seed;
  for (let i = 0; i < dimensions; i++) {
    state = (state * 1664525 + 1013904223) % 2147483647;
    vector.push((state / 2147483647) * 2 - 1);
  }
  const magnitude = Math.sqrt(vector.reduce((sum, value) => sum + value * value, 0));
  return vector.map((value) => value / magnitude);
}

export function seededBreakdown(seed: number): FeatureBreakdown {
  const next = (offset: number) => 70 + ((seed + offset) % 31);
  return {
    faceShape: next(1),
    eyes: next(2),
    eyebrows: next(3),
    nose: next(4),
    lips: next(5),
    smile: next(6),
    forehead: next(7),
    jawline: next(8),
    hairline: next(9),
  };
}

function hashString(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i++) {
    hash = (hash * 31 + value.charCodeAt(i)) % 2147483647;
  }
  return hash;
}

export function celebrityToProfile(celebrity: CelebritySeed): Profile & { storedFeatures: FeatureBreakdown } {
  const seed = hashString(celebrity.slug);
  const images = [
    {
      id: `${celebrity.slug}-primary`,
      url: celebrity.imageUrl,
      alt: `${celebrity.fullName} portrait`,
      isPrimary: true,
      width: 640,
      height: 800,
    },
    ...(celebrity.extraImages ?? []).map((url, index) => ({
      id: `${celebrity.slug}-extra-${index + 1}`,
      url,
      alt: `${celebrity.fullName} photo ${index + 2}`,
      isPrimary: false,
      width: 640,
      height: 800,
    })),
  ];

  return {
    id: crypto.randomUUID(),
    slug: celebrity.slug,
    fullName: celebrity.fullName,
    gender: celebrity.gender,
    dateOfBirth: celebrity.dateOfBirth,
    nationality: celebrity.nationality,
    country: celebrity.country,
    city: celebrity.city,
    occupation: celebrity.occupation,
    biography: celebrity.biography,
    heightCm: celebrity.heightCm,
    eyeColor: celebrity.eyeColor,
    hairColor: celebrity.hairColor,
    ethnicityCategory: celebrity.ethnicityCategory,
    publicFigureCategory: celebrity.category,
    instagramUrl: celebrity.instagramUrl,
    xUrl: celebrity.xUrl,
    websiteUrl: `https://twinzy.demo/profile/${celebrity.slug}`,
    images,
    tags: celebrity.tags,
    faceEmbedding: seededVector(seed),
    popularityScore: celebrity.popularityScore,
    isFunnyObject: false,
    storedFeatures: seededBreakdown(seed),
  };
}

export function funnyObjectToProfile(
  object: (typeof FUNNY_OBJECT_SEEDS)[number],
  index: number,
): Profile & { storedFeatures: FeatureBreakdown } {
  const seed = 50000 + index * 313;
  return {
    id: crypto.randomUUID(),
    slug: object.slug,
    fullName: object.name,
    gender: "other",
    dateOfBirth: "2000-01-01",
    nationality: "Everywhere",
    country: "Kitchen",
    city: "Pantry",
    occupation: `Legendary ${object.name}`,
    biography: `${object.name} ${object.emoji} is an iconic funny object admired for its instantly recognizable shape.`,
    heightCm: null,
    eyeColor: "N/A",
    hairColor: "N/A",
    ethnicityCategory: "Object",
    publicFigureCategory: "funny_object",
    images: [
      {
        id: `${object.slug}-primary`,
        url: object.imageUrl,
        alt: object.name,
        isPrimary: true,
        width: 640,
        height: 640,
      },
    ],
    tags: object.tags,
    faceEmbedding: seededVector(seed),
    popularityScore: 25 + (seed % 20),
    isFunnyObject: true,
    storedFeatures: seededBreakdown(seed),
  };
}
