import type { FeatureBreakdown, Gender, Profile, ProfileCategory } from "@twinzy/types";

export interface CelebritySeed {
  fullName: string;
  slug: string;
  category: ProfileCategory;
  gender: Gender;
  dateOfBirth: string;
  nationality: string;
  country: string;
  city: string;
  occupation: string;
  biography: string;
  heightCm: number | null;
  eyeColor: string;
  hairColor: string;
  ethnicityCategory: string;
  imageUrl: string;
  extraImages?: string[];
  tags: string[];
  instagramUrl?: string;
  xUrl?: string;
  popularityScore: number;
}

export const REAL_CELEBRITIES: CelebritySeed[] = [
  {
    fullName: "Leonardo DiCaprio",
    slug: "leonardo-dicaprio",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1974-11-11",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actor",
    biography: "Leonardo DiCaprio is an Academy Award-winning actor known for Titanic, Inception, and The Revenant.",
    heightCm: 183,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Leonardo_DiCaprio_Cannes_2019.jpg",
    tags: ["oscar", "hollywood", "blockbuster"],
    popularityScore: 98,
  },
  {
    fullName: "Brad Pitt",
    slug: "brad-pitt",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1963-12-18",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actor",
    biography: "Brad Pitt is a Hollywood legend starring in Fight Club, Ocean's Eleven, and Once Upon a Time in Hollywood.",
    heightCm: 180,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Brad_Pitt-69858.jpg",
    tags: ["hollywood", "producer", "icon"],
    popularityScore: 97,
  },
  {
    fullName: "Tom Hanks",
    slug: "tom-hanks",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1956-07-09",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actor",
    biography: "Tom Hanks is one of America's most beloved actors, known for Forrest Gump and Saving Private Ryan.",
    heightCm: 183,
    eyeColor: "Blue",
    hairColor: "Gray",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Tom_Hanks_TIFF_2019.jpg",
    tags: ["oscar", "everyman", "classic"],
    popularityScore: 96,
  },
  {
    fullName: "Ryan Gosling",
    slug: "ryan-gosling",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1980-11-12",
    nationality: "Canadian",
    country: "Canada",
    city: "Toronto",
    occupation: "Actor",
    biography: "Ryan Gosling rose to fame with The Notebook and La La Land, becoming a modern romantic lead.",
    heightCm: 184,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Ryan_Gosling_-_Pale_Blue_Dot.jpg",
    tags: ["romance", "indie", "hollywood"],
    popularityScore: 92,
  },
  {
    fullName: "Margot Robbie",
    slug: "margot-robbie",
    category: "actor_hollywood",
    gender: "female",
    dateOfBirth: "1990-07-02",
    nationality: "Australian",
    country: "Australia",
    city: "Gold Coast",
    occupation: "Actress",
    biography: "Margot Robbie starred in Barbie and The Wolf of Wall Street, becoming one of Hollywood's biggest stars.",
    heightCm: 168,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/50/Margot_Robbie_at_Sundance_2015.jpg",
    tags: ["barbie", "hollywood", "producer"],
    popularityScore: 94,
  },
  {
    fullName: "Denzel Washington",
    slug: "denzel-washington",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1954-12-28",
    nationality: "American",
    country: "United States",
    city: "New York",
    occupation: "Actor",
    biography: "Denzel Washington is a two-time Oscar winner known for Training Day, Malcolm X, and Fences.",
    heightCm: 185,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Denzel_Washington_cropped_02.jpg",
    tags: ["oscar", "drama", "legend"],
    popularityScore: 95,
  },
  {
    fullName: "Robert Downey Jr.",
    slug: "robert-downey-jr",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1965-04-04",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actor",
    biography: "Robert Downey Jr. reinvented his career as Iron Man, anchoring the Marvel Cinematic Universe.",
    heightCm: 174,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/23/Robert_Downey_Jr_2014_Comic_Con_%28cropped%29.jpg",
    tags: ["iron man", "marvel", "comeback"],
    popularityScore: 96,
  },
  {
    fullName: "Chris Hemsworth",
    slug: "chris-hemsworth",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1983-08-11",
    nationality: "Australian",
    country: "Australia",
    city: "Melbourne",
    occupation: "Actor",
    biography: "Chris Hemsworth plays Thor in the Marvel Cinematic Universe and is known for his action roles.",
    heightCm: 190,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Chris_Hemsworth_by_Gage_Skidmore.jpg",
    tags: ["marvel", "thor", "action"],
    popularityScore: 93,
  },
  {
    fullName: "Keanu Reeves",
    slug: "keanu-reeves",
    category: "actor_hollywood",
    gender: "male",
    dateOfBirth: "1964-09-02",
    nationality: "Canadian",
    country: "Canada",
    city: "Toronto",
    occupation: "Actor",
    biography: "Keanu Reeves is beloved for The Matrix, John Wick, and his wholesome internet fame.",
    heightCm: 186,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Keanu_Reeves_%28crop_and_levels%29.jpg",
    tags: ["john wick", "matrix", "wholesome"],
    popularityScore: 96,
  },
  {
    fullName: "Meryl Streep",
    slug: "meryl-streep",
    category: "actor_hollywood",
    gender: "female",
    dateOfBirth: "1949-06-22",
    nationality: "American",
    country: "United States",
    city: "New York",
    occupation: "Actress",
    biography: "Meryl Streep holds the record for most Oscar nominations and is celebrated for her versatility.",
    heightCm: 168,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Meryl_Streep_December_2014.jpg",
    tags: ["oscar", "legend", "drama"],
    popularityScore: 94,
  },
  {
    fullName: "Scarlett Johansson",
    slug: "scarlett-johansson",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1984-11-22",
    nationality: "American",
    country: "United States",
    city: "New York",
    occupation: "Actress",
    biography: "Scarlett Johansson is a global superstar known for Lost in Translation and the Marvel Cinematic Universe.",
    heightCm: 160,
    eyeColor: "Green",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Scarlett_Johansson-8588.jpg",
    tags: ["marvel", "hollywood", "action"],
    popularityScore: 95,
  },
  {
    fullName: "Emma Stone",
    slug: "emma-stone",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1988-11-06",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actress",
    biography: "Emma Stone won an Oscar for La La Land and charmed audiences in Easy A and The Favourite.",
    heightCm: 168,
    eyeColor: "Green",
    hairColor: "Red",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/Emma_Stone-2468.jpg",
    tags: ["oscar", "comedy", "hollywood"],
    popularityScore: 91,
  },
  {
    fullName: "Angelina Jolie",
    slug: "angelina-jolie",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1975-06-04",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actress",
    biography: "Angelina Jolie is an Oscar-winning actress, filmmaker, and humanitarian known for Lara Croft and Maleficent.",
    heightCm: 169,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/Angelina_Jolie_Global_Summit_2014.jpg",
    tags: ["humanitarian", "action", "hollywood"],
    popularityScore: 93,
  },
  {
    fullName: "Zendaya",
    slug: "zendaya",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1996-09-01",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actress",
    biography: "Zendaya is an Emmy-winning actress and fashion icon starring in Euphoria and Spider-Man.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/28/Zendaya_-_2019_by_Glenn_Francis.jpg",
    tags: ["euphoria", "fashion", "spider-man"],
    popularityScore: 94,
  },
  {
    fullName: "Natalie Portman",
    slug: "natalie-portman",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1981-06-09",
    nationality: "Israeli-American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actress",
    biography: "Natalie Portman won an Oscar for Black Swan and starred in Star Wars and Thor.",
    heightCm: 160,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Natalie_Portman_Cannes_2015_5.jpg",
    tags: ["oscar", "star wars", "drama"],
    popularityScore: 90,
  },
  {
    fullName: "Lupita Nyong'o",
    slug: "lupita-nyongo",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1983-03-01",
    nationality: "Kenyan-Mexican",
    country: "Kenya",
    city: "Nairobi",
    occupation: "Actress",
    biography: "Lupita Nyong'o won an Oscar for 12 Years a Slave and starred in Black Panther.",
    heightCm: 165,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Lupita_Nyong%27o_by_Gage_Skidmore.jpg",
    tags: ["oscar", "black panther", "fashion"],
    popularityScore: 89,
  },
  {
    fullName: "Penelope Cruz",
    slug: "penelope-cruz",
    category: "actress_worldwide",
    gender: "female",
    dateOfBirth: "1974-04-28",
    nationality: "Spanish",
    country: "Spain",
    city: "Madrid",
    occupation: "Actress",
    biography: "Penelope Cruz is an Oscar-winning Spanish actress known for Vicky Cristina Barcelona and Volver.",
    heightCm: 163,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Latino",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Pen%C3%A9lope_Cruz_at_the_2014_Toronto_International_Film_Festival.jpg",
    tags: ["spanish cinema", "oscar", "european"],
    popularityScore: 88,
  },
  {
    fullName: "Shah Rukh Khan",
    slug: "shah-rukh-khan",
    category: "actor_bollywood",
    gender: "male",
    dateOfBirth: "1965-11-02",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actor",
    biography: "Shah Rukh Khan is the King of Bollywood with a career spanning decades of blockbuster romance and drama.",
    heightCm: 173,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Shahrukh_Khan_graces_the_launch_of_the_new_Santro.jpg",
    tags: ["bollywood", "king khan", "romance"],
    popularityScore: 99,
  },
  {
    fullName: "Deepika Padukone",
    slug: "deepika-padukone",
    category: "actor_bollywood",
    gender: "female",
    dateOfBirth: "1986-01-05",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actress",
    biography: "Deepika Padukone is one of India's highest-paid actresses and a global fashion icon.",
    heightCm: 174,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Deepika_Padukone_at_Chhapaak_promotions.jpg",
    tags: ["bollywood", "fashion", "global"],
    popularityScore: 94,
  },
  {
    fullName: "Amitabh Bachchan",
    slug: "amitabh-bachchan",
    category: "actor_bollywood",
    gender: "male",
    dateOfBirth: "1942-10-11",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actor",
    biography: "Amitabh Bachchan is the Big B of Bollywood, a towering figure in Indian cinema for over five decades.",
    heightCm: 188,
    eyeColor: "Brown",
    hairColor: "Gray",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Amitabh_Bachchan_December_2013.jpg",
    tags: ["bollywood", "legend", "big b"],
    popularityScore: 97,
  },
  {
    fullName: "Priyanka Chopra",
    slug: "priyanka-chopra",
    category: "actor_bollywood",
    gender: "female",
    dateOfBirth: "1982-07-18",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actress",
    biography: "Priyanka Chopra transitioned from Miss World to Bollywood stardom and Hollywood success.",
    heightCm: 169,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Priyanka_Chopra_at_Bulgary_event%2C_2019.jpg",
    tags: ["bollywood", "global", "producer"],
    popularityScore: 92,
  },
  {
    fullName: "Ranveer Singh",
    slug: "ranveer-singh",
    category: "actor_bollywood",
    gender: "male",
    dateOfBirth: "1985-07-06",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actor",
    biography: "Ranveer Singh is known for his energetic performances in Gully Boy, Padmaavat, and Bajirao Mastani.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Ranveer_Singh_promoting_Gully_Boy.jpg",
    tags: ["bollywood", "energy", "box office"],
    popularityScore: 90,
  },
  {
    fullName: "Alia Bhatt",
    slug: "alia-bhatt",
    category: "actor_bollywood",
    gender: "female",
    dateOfBirth: "1993-03-15",
    nationality: "Indian",
    country: "India",
    city: "Mumbai",
    occupation: "Actress",
    biography: "Alia Bhatt is a leading Bollywood actress acclaimed for Gangubai Kathiawadi and Raazi.",
    heightCm: 160,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "South Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/14/Alia_Bhatt_at_Brahmastra_promotions.jpg",
    tags: ["bollywood", "rising star", "drama"],
    popularityScore: 91,
  },
  {
    fullName: "Adel Emam",
    slug: "adel-emam",
    category: "actor_egyptian",
    gender: "male",
    dateOfBirth: "1940-05-17",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actor",
    biography: "Adel Emam is Egypt's most celebrated actor, known as the Zaeem with decades of comedy and drama classics.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Gray",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Adel_Emam.jpg",
    tags: ["egyptian cinema", "comedy", "legend"],
    popularityScore: 97,
  },
  {
    fullName: "Ahmed Helmy",
    slug: "ahmed-helmy",
    category: "actor_egyptian",
    gender: "male",
    dateOfBirth: "1969-11-18",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actor",
    biography: "Ahmed Helmy is one of Egypt's top comedy actors, beloved for his expressive performances and wit.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Ahmed_Helmy.jpg",
    tags: ["egyptian comedy", "box office", "star"],
    popularityScore: 93,
  },
  {
    fullName: "Yousra",
    slug: "yousra",
    category: "actor_egyptian",
    gender: "female",
    dateOfBirth: "1955-03-17",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actress",
    biography: "Yousra is an iconic Egyptian actress and singer with a legendary career in Arab cinema.",
    heightCm: 165,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Yousra.jpg",
    tags: ["egyptian cinema", "diva", "classic"],
    popularityScore: 92,
  },
  {
    fullName: "Nelly Karim",
    slug: "nelly-karim",
    category: "actor_egyptian",
    gender: "female",
    dateOfBirth: "1974-12-18",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Alexandria",
    occupation: "Actress",
    biography: "Nelly Karim is an acclaimed Egyptian actress known for powerful roles in contemporary Arab cinema.",
    heightCm: 168,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Nelly_Karim.jpg",
    tags: ["egyptian cinema", "drama", "award winner"],
    popularityScore: 88,
  },
  {
    fullName: "Mohamed Henedy",
    slug: "mohamed-henedy",
    category: "actor_egyptian",
    gender: "male",
    dateOfBirth: "1969-02-01",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actor",
    biography: "Mohamed Henedy is a beloved Egyptian comedian and actor famous for his slapstick humor and wit.",
    heightCm: 170,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Mohamed_Henedy.jpg",
    tags: ["egyptian comedy", "stand-up", "star"],
    popularityScore: 89,
  },
  {
    fullName: "Mona Zaki",
    slug: "mona-zaki",
    category: "actor_egyptian",
    gender: "female",
    dateOfBirth: "1976-11-18",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Actress",
    biography: "Mona Zaki is one of Egypt's most popular actresses, known for versatile roles in film and television.",
    heightCm: 165,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Mona_Zaki.jpg",
    tags: ["egyptian cinema", "television", "star"],
    popularityScore: 87,
  },
  {
    fullName: "Kivanc Tatlitug",
    slug: "kivanc-tatlitug",
    category: "actor_turkish",
    gender: "male",
    dateOfBirth: "1983-12-27",
    nationality: "Turkish",
    country: "Turkey",
    city: "Istanbul",
    occupation: "Actor",
    biography: "Kivanc Tatlitug is a Turkish heartthrob famous for Kurt Seyit ve Sura and international dizi fame.",
    heightCm: 187,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0c/K%C4%B1van%C3%A7_Tatlıtu%C4%9F.jpg",
    tags: ["dizi", "turkish", "romance"],
    popularityScore: 90,
  },
  {
    fullName: "Burak Ozcivit",
    slug: "burak-ozcivit",
    category: "actor_turkish",
    gender: "male",
    dateOfBirth: "1984-12-24",
    nationality: "Turkish",
    country: "Turkey",
    city: "Istanbul",
    occupation: "Actor",
    biography: "Burak Ozcivit starred in Calikusu and Kurulus Osman, becoming a global Turkish drama icon.",
    heightCm: 184,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Burak_%C3%96z%C3%A7ivit.jpg",
    tags: ["dizi", "turkish", "historical"],
    popularityScore: 89,
  },
  {
    fullName: "Hande Ercel",
    slug: "hande-ercel",
    category: "actor_turkish",
    gender: "female",
    dateOfBirth: "1993-11-24",
    nationality: "Turkish",
    country: "Turkey",
    city: "Istanbul",
    occupation: "Actress",
    biography: "Hande Ercel rose to fame with Hayat Bazen Tatlidir and became one of Turkey's top dizi stars.",
    heightCm: 170,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Hande_Er%C3%A7el.jpg",
    tags: ["dizi", "turkish", "romance"],
    popularityScore: 88,
  },
  {
    fullName: "Can Yaman",
    slug: "can-yaman",
    category: "actor_turkish",
    gender: "male",
    dateOfBirth: "1989-11-08",
    nationality: "Turkish",
    country: "Turkey",
    city: "Istanbul",
    occupation: "Actor",
    biography: "Can Yaman gained international fame with Erkenci Kus and Bay Yanlis, charming audiences worldwide.",
    heightCm: 185,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Can_Yaman.jpg",
    tags: ["dizi", "turkish", "international"],
    popularityScore: 87,
  },
  {
    fullName: "Gong Yoo",
    slug: "gong-yoo",
    category: "actor_korean",
    gender: "male",
    dateOfBirth: "1979-07-10",
    nationality: "Korean",
    country: "South Korea",
    city: "Seoul",
    occupation: "Actor",
    biography: "Gong Yoo became a global sensation with Train to Busan and the hit series Goblin.",
    heightCm: 184,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Gong_Yoo_2016.jpg",
    tags: ["kdrama", "hallyu", "goblin"],
    popularityScore: 94,
  },
  {
    fullName: "Song Hye-kyo",
    slug: "song-hye-kyo",
    category: "actor_korean",
    gender: "female",
    dateOfBirth: "1981-11-22",
    nationality: "Korean",
    country: "South Korea",
    city: "Seoul",
    occupation: "Actress",
    biography: "Song Hye-kyo is a leading Korean actress known for Descendants of the Sun and global brand campaigns.",
    heightCm: 161,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/Song_Hye-kyo_2016.jpg",
    tags: ["kdrama", "beauty", "global"],
    popularityScore: 93,
  },
  {
    fullName: "Lee Min-ho",
    slug: "lee-min-ho",
    category: "actor_korean",
    gender: "male",
    dateOfBirth: "1987-06-22",
    nationality: "Korean",
    country: "South Korea",
    city: "Seoul",
    occupation: "Actor",
    biography: "Lee Min-ho became a Hallyu superstar with Boys Over Flowers and The King: Eternal Monarch.",
    heightCm: 187,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Lee_Min-ho_at_2019_Asia_Artist_Awards.jpg",
    tags: ["kdrama", "hallyu", "romance"],
    popularityScore: 92,
  },
  {
    fullName: "Park Seo-joon",
    slug: "park-seo-joon",
    category: "actor_korean",
    gender: "male",
    dateOfBirth: "1988-12-16",
    nationality: "Korean",
    country: "South Korea",
    city: "Seoul",
    occupation: "Actor",
    biography: "Park Seo-joon starred in Itaewon Class and What's Wrong with Secretary Kim, gaining global fans.",
    heightCm: 185,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Park_Seo-joon_at_the_2022_Busan_International_Film_Festival.jpg",
    tags: ["kdrama", "hallyu", "romcom"],
    popularityScore: 91,
  },
  {
    fullName: "Mohamed Salah",
    slug: "mohamed-salah",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1992-06-15",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Footballer",
    biography: "Mohamed Salah is Egypt's football king and a Liverpool legend, adored across the Arab world and Europe.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Mohamed_Salah_2018.jpg",
    tags: ["premier league", "egypt", "football"],
    popularityScore: 98,
  },
  {
    fullName: "Lionel Messi",
    slug: "lionel-messi",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1987-06-24",
    nationality: "Argentine",
    country: "Argentina",
    city: "Rosario",
    occupation: "Footballer",
    biography: "Lionel Messi is widely regarded as one of the greatest footballers of all time and a World Cup champion.",
    heightCm: 170,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Latino",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg",
    tags: ["world cup", "barcelona", "goat"],
    popularityScore: 99,
  },
  {
    fullName: "Cristiano Ronaldo",
    slug: "cristiano-ronaldo",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1985-02-05",
    nationality: "Portuguese",
    country: "Portugal",
    city: "Funchal",
    occupation: "Footballer",
    biography: "Cristiano Ronaldo is a global football icon with records across Manchester United, Real Madrid, and beyond.",
    heightCm: 187,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg",
    tags: ["real madrid", "portugal", "legend"],
    popularityScore: 99,
  },
  {
    fullName: "Neymar",
    slug: "neymar",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1992-02-05",
    nationality: "Brazilian",
    country: "Brazil",
    city: "Sao Paulo",
    occupation: "Footballer",
    biography: "Neymar is a Brazilian superstar known for flair, skill, and stints at Barcelona, PSG, and Al Hilal.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Latino",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/be/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03.jpg",
    tags: ["brazil", "skill", "samba"],
    popularityScore: 97,
  },
  {
    fullName: "Kylian Mbappe",
    slug: "kylian-mbappe",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "1998-12-20",
    nationality: "French",
    country: "France",
    city: "Paris",
    occupation: "Footballer",
    biography: "Kylian Mbappe is a generational French talent who won the World Cup and dominates at Paris Saint-Germain.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/51/Kylian_Mbapp%C3%A9_%28cropped%29.jpg",
    tags: ["france", "world cup", "speed"],
    popularityScore: 96,
  },
  {
    fullName: "Erling Haaland",
    slug: "erling-haaland",
    category: "athlete_football",
    gender: "male",
    dateOfBirth: "2000-07-21",
    nationality: "Norwegian",
    country: "Norway",
    city: "Leeds",
    occupation: "Footballer",
    biography: "Erling Haaland is a prolific striker for Manchester City and Norway, breaking scoring records at pace.",
    heightCm: 194,
    eyeColor: "Brown",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/07/Erling_Haaland_2023.jpg",
    tags: ["manchester city", "striker", "records"],
    popularityScore: 94,
  },
  {
    fullName: "LeBron James",
    slug: "lebron-james",
    category: "athlete_basketball",
    gender: "male",
    dateOfBirth: "1984-12-30",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Basketball Player",
    biography: "LeBron James is an NBA superstar and four-time champion known as King James.",
    heightCm: 206,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/LeBron_James_Lakers.jpg",
    tags: ["nba", "lakers", "champion"],
    popularityScore: 97,
  },
  {
    fullName: "Stephen Curry",
    slug: "stephen-curry",
    category: "athlete_basketball",
    gender: "male",
    dateOfBirth: "1988-03-14",
    nationality: "American",
    country: "United States",
    city: "San Francisco",
    occupation: "Basketball Player",
    biography: "Stephen Curry revolutionized basketball with his three-point shooting for the Golden State Warriors.",
    heightCm: 188,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/36/Stephen_Curry_dribbling_2016_%28cropped%29.jpg",
    tags: ["nba", "warriors", "three-pointer"],
    popularityScore: 95,
  },
  {
    fullName: "Michael Jordan",
    slug: "michael-jordan",
    category: "athlete_basketball",
    gender: "male",
    dateOfBirth: "1963-02-17",
    nationality: "American",
    country: "United States",
    city: "Chicago",
    occupation: "Basketball Player",
    biography: "Michael Jordan is widely considered the greatest basketball player ever, leading the Chicago Bulls to six titles.",
    heightCm: 198,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg",
    tags: ["nba", "bulls", "goat"],
    popularityScore: 98,
  },
  {
    fullName: "Giannis Antetokounmpo",
    slug: "giannis-antetokounmpo",
    category: "athlete_basketball",
    gender: "male",
    dateOfBirth: "1994-12-06",
    nationality: "Greek",
    country: "Greece",
    city: "Athens",
    occupation: "Basketball Player",
    biography: "Giannis Antetokounmpo is the Greek Freak, an NBA MVP and champion with the Milwaukee Bucks.",
    heightCm: 211,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Giannis_Antetokounmpo_2019_%28cropped%29.jpg",
    tags: ["nba", "bucks", "mvp"],
    popularityScore: 93,
  },
  {
    fullName: "Serena Williams",
    slug: "serena-williams",
    category: "athlete_tennis",
    gender: "female",
    dateOfBirth: "1981-09-26",
    nationality: "American",
    country: "United States",
    city: "Palm Beach",
    occupation: "Tennis Player",
    biography: "Serena Williams dominated women's tennis with 23 Grand Slam singles titles.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Serena_Williams_at_2013_US_Open.jpg",
    tags: ["grand slam", "tennis", "legend"],
    popularityScore: 95,
  },
  {
    fullName: "Rafael Nadal",
    slug: "rafael-nadal",
    category: "athlete_tennis",
    gender: "male",
    dateOfBirth: "1986-06-03",
    nationality: "Spanish",
    country: "Spain",
    city: "Manacor",
    occupation: "Tennis Player",
    biography: "Rafael Nadal is the King of Clay with a record 14 French Open titles and 22 Grand Slams.",
    heightCm: 185,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Latino",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/71/Rafael_Nadal_%2830150109981%29_%28cropped%29.jpg",
    tags: ["clay court", "grand slam", "spain"],
    popularityScore: 96,
  },
  {
    fullName: "Novak Djokovic",
    slug: "novak-djokovic",
    category: "athlete_tennis",
    gender: "male",
    dateOfBirth: "1987-05-22",
    nationality: "Serbian",
    country: "Serbia",
    city: "Belgrade",
    occupation: "Tennis Player",
    biography: "Novak Djokovic holds the record for most Grand Slam men's singles titles in the Open Era.",
    heightCm: 188,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/48/Novak_Djokovic_Trophy_Wimbledon_2019_%28cropped%29.jpg",
    tags: ["grand slam", "serbia", "goat"],
    popularityScore: 95,
  },
  {
    fullName: "Naomi Osaka",
    slug: "naomi-osaka",
    category: "athlete_tennis",
    gender: "female",
    dateOfBirth: "1997-10-16",
    nationality: "Japanese",
    country: "Japan",
    city: "Osaka",
    occupation: "Tennis Player",
    biography: "Naomi Osaka is a four-time Grand Slam champion and a powerful voice for mental health in sports.",
    heightCm: 180,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Asian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Naomi_Osaka_%2835199830643%29_%28cropped%29.jpg",
    tags: ["grand slam", "japan", "champion"],
    popularityScore: 90,
  },
  {
    fullName: "Conor McGregor",
    slug: "conor-mcgregor",
    category: "athlete_mma",
    gender: "male",
    dateOfBirth: "1988-07-14",
    nationality: "Irish",
    country: "Ireland",
    city: "Dublin",
    occupation: "MMA Fighter",
    biography: "Conor McGregor became the UFC's biggest star with his knockout power and brash personality.",
    heightCm: 175,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Conor_McGregor_2015.jpg",
    tags: ["ufc", "ireland", "knockout"],
    popularityScore: 94,
  },
  {
    fullName: "Khabib Nurmagomedov",
    slug: "khabib-nurmagomedov",
    category: "athlete_mma",
    gender: "male",
    dateOfBirth: "1988-09-20",
    nationality: "Russian",
    country: "Russia",
    city: "Makhachkala",
    occupation: "MMA Fighter",
    biography: "Khabib Nurmagomedov retired undefeated as UFC lightweight champion with 29 wins and no losses.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Khabib_Nurmagomedov_2018.jpg",
    tags: ["ufc", "undefeated", "russia"],
    popularityScore: 93,
  },
  {
    fullName: "Ronda Rousey",
    slug: "ronda-rousey",
    category: "athlete_mma",
    gender: "female",
    dateOfBirth: "1987-02-01",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "MMA Fighter",
    biography: "Ronda Rousey pioneered women's MMA and became the first UFC women's bantamweight champion.",
    heightCm: 170,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Ronda_Rousey_2015.jpg",
    tags: ["ufc", "pioneer", "judo"],
    popularityScore: 88,
  },
  {
    fullName: "Usain Bolt",
    slug: "usain-bolt",
    category: "athlete_olympics",
    gender: "male",
    dateOfBirth: "1986-08-21",
    nationality: "Jamaican",
    country: "Jamaica",
    city: "Kingston",
    occupation: "Sprinter",
    biography: "Usain Bolt is the fastest man in history, winning eight Olympic gold medals in sprint events.",
    heightCm: 195,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Usain_Bolt_after_200m_final_2012.jpg",
    tags: ["sprint", "olympics", "world record"],
    popularityScore: 96,
  },
  {
    fullName: "Simone Biles",
    slug: "simone-biles",
    category: "athlete_olympics",
    gender: "female",
    dateOfBirth: "1997-03-14",
    nationality: "American",
    country: "United States",
    city: "Houston",
    occupation: "Gymnast",
    biography: "Simone Biles is the most decorated American gymnast with gravity-defying skills and Olympic gold.",
    heightCm: 142,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Simone_Biles%2C_2016_Olympics.jpg",
    tags: ["gymnastics", "olympics", "goat"],
    popularityScore: 94,
  },
  {
    fullName: "Michael Phelps",
    slug: "michael-phelps",
    category: "athlete_olympics",
    gender: "male",
    dateOfBirth: "1985-06-30",
    nationality: "American",
    country: "United States",
    city: "Baltimore",
    occupation: "Swimmer",
    biography: "Michael Phelps won 23 Olympic gold medals, the most of any athlete in history.",
    heightCm: 193,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Michael_Phelps_Rio_Olympics_2016.jpg",
    tags: ["swimming", "olympics", "gold medals"],
    popularityScore: 93,
  },
  {
    fullName: "Taylor Swift",
    slug: "taylor-swift",
    category: "singer",
    gender: "female",
    dateOfBirth: "1989-12-13",
    nationality: "American",
    country: "United States",
    city: "Nashville",
    occupation: "Singer",
    biography: "Taylor Swift is a record-breaking pop superstar known for storytelling and the Eras Tour.",
    heightCm: 180,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png",
    tags: ["pop", "eras tour", "songwriter"],
    popularityScore: 99,
  },
  {
    fullName: "Beyonce",
    slug: "beyonce",
    category: "singer",
    gender: "female",
    dateOfBirth: "1981-09-04",
    nationality: "American",
    country: "United States",
    city: "Houston",
    occupation: "Singer",
    biography: "Beyonce is a global music icon, performer, and cultural force behind Destiny's Child and solo stardom.",
    heightCm: 169,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png",
    tags: ["r&b", "queen bey", "performer"],
    popularityScore: 98,
  },
  {
    fullName: "Amr Diab",
    slug: "amr-diab",
    category: "singer",
    gender: "male",
    dateOfBirth: "1961-10-11",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Cairo",
    occupation: "Singer",
    biography: "Amr Diab is the father of Mediterranean music and Egypt's best-selling artist of all time.",
    heightCm: 178,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Amr_Diab_2017.jpg",
    tags: ["arabic pop", "egypt", "tamally maak"],
    popularityScore: 96,
  },
  {
    fullName: "Nancy Ajram",
    slug: "nancy-ajram",
    category: "singer",
    gender: "female",
    dateOfBirth: "1983-05-16",
    nationality: "Lebanese",
    country: "Lebanon",
    city: "Beirut",
    occupation: "Singer",
    biography: "Nancy Ajram is one of the Arab world's biggest pop stars with hits spanning two decades.",
    heightCm: 168,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Nancy_Ajram.jpg",
    tags: ["arabic pop", "lebanon", "diva"],
    popularityScore: 94,
  },
  {
    fullName: "Rihanna",
    slug: "rihanna",
    category: "singer",
    gender: "female",
    dateOfBirth: "1988-02-20",
    nationality: "Barbadian",
    country: "Barbados",
    city: "Bridgetown",
    occupation: "Singer",
    biography: "Rihanna is a global pop and R&B icon, entrepreneur, and founder of Fenty Beauty.",
    heightCm: 173,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/16/Rihanna_Fenty_2018.png",
    tags: ["r&b", "fenty", "pop"],
    popularityScore: 97,
  },
  {
    fullName: "Shakira",
    slug: "shakira",
    category: "singer",
    gender: "female",
    dateOfBirth: "1977-02-02",
    nationality: "Colombian",
    country: "Colombia",
    city: "Barranquilla",
    occupation: "Singer",
    biography: "Shakira is a Colombian superstar known for Hips Don't Lie and her global Latin pop crossover.",
    heightCm: 157,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Latino",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Shakira_2014.jpg",
    tags: ["latin pop", "world cup", "dancer"],
    popularityScore: 95,
  },
  {
    fullName: "Fairuz",
    slug: "fairuz",
    category: "singer",
    gender: "female",
    dateOfBirth: "1934-11-21",
    nationality: "Lebanese",
    country: "Lebanon",
    city: "Beirut",
    occupation: "Singer",
    biography: "Fairuz is the voice of Lebanon and the Arab world, with a career spanning over six decades.",
    heightCm: null,
    eyeColor: "Brown",
    hairColor: "Gray",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Fairuz.jpg",
    tags: ["arabic music", "legend", "lebanon"],
    popularityScore: 92,
  },
  {
    fullName: "MrBeast",
    slug: "mrbeast",
    category: "influencer",
    gender: "male",
    dateOfBirth: "1998-05-07",
    nationality: "American",
    country: "United States",
    city: "Greenville",
    occupation: "YouTuber",
    biography: "MrBeast is the world's most subscribed individual YouTuber, famous for massive giveaways and stunts.",
    heightCm: 191,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/MrBeast_2023.jpg",
    tags: ["youtube", "viral", "philanthropy"],
    popularityScore: 96,
  },
  {
    fullName: "Khaby Lame",
    slug: "khaby-lame",
    category: "influencer",
    gender: "male",
    dateOfBirth: "2000-03-09",
    nationality: "Senegalese",
    country: "Italy",
    city: "Chivasso",
    occupation: "TikToker",
    biography: "Khaby Lame became the most-followed person on TikTok with his silent comedy reactions.",
    heightCm: 185,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/KhabyLame.jpg",
    tags: ["tiktok", "comedy", "viral"],
    popularityScore: 93,
  },
  {
    fullName: "Charli D'Amelio",
    slug: "charli-damelio",
    category: "influencer",
    gender: "female",
    dateOfBirth: "2004-05-01",
    nationality: "American",
    country: "United States",
    city: "Norwalk",
    occupation: "TikToker",
    biography: "Charli D'Amelio rose to fame as one of TikTok's earliest and biggest dance creators.",
    heightCm: 170,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Charli_D%27Amelio_2021.jpg",
    tags: ["tiktok", "dance", "gen z"],
    popularityScore: 90,
  },
  {
    fullName: "PewDiePie",
    slug: "pewdiepie",
    category: "influencer",
    gender: "male",
    dateOfBirth: "1989-10-24",
    nationality: "Swedish",
    country: "Sweden",
    city: "Gothenburg",
    occupation: "YouTuber",
    biography: "PewDiePie was YouTube's most-subscribed individual creator, pioneering gaming commentary culture.",
    heightCm: 177,
    eyeColor: "Blue",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/86/PewDiePie_at_Pax_2015.jpg",
    tags: ["youtube", "gaming", "sweden"],
    popularityScore: 91,
  },
  {
    fullName: "Albert Einstein",
    slug: "albert-einstein",
    category: "historical",
    gender: "male",
    dateOfBirth: "1879-03-14",
    nationality: "German",
    country: "Germany",
    city: "Ulm",
    occupation: "Physicist",
    biography: "Albert Einstein developed the theory of relativity and became the most famous scientist in history.",
    heightCm: 175,
    eyeColor: "Brown",
    hairColor: "Gray",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Albert_Einstein_Head.jpg",
    tags: ["physics", "genius", "history"],
    popularityScore: 99,
  },
  {
    fullName: "Cleopatra VII",
    slug: "cleopatra",
    category: "historical",
    gender: "female",
    dateOfBirth: "0069-01-01",
    nationality: "Egyptian",
    country: "Egypt",
    city: "Alexandria",
    occupation: "Queen",
    biography: "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt and a timeless icon.",
    heightCm: null,
    eyeColor: "Brown",
    hairColor: "Black",
    ethnicityCategory: "Middle Eastern",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Kleopatra-VII.-Altes-Museum-Berlin1.jpg",
    tags: ["ancient egypt", "queen", "history"],
    popularityScore: 95,
  },
  {
    fullName: "Marilyn Monroe",
    slug: "marilyn-monroe",
    category: "historical",
    gender: "female",
    dateOfBirth: "1926-06-01",
    nationality: "American",
    country: "United States",
    city: "Los Angeles",
    occupation: "Actress",
    biography: "Marilyn Monroe became a cultural icon of glamour, starring in Some Like It Hot and Gentlemen Prefer Blondes.",
    heightCm: 166,
    eyeColor: "Blue",
    hairColor: "Blonde",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Marilyn_Monroe_in_1953.jpg",
    tags: ["hollywood", "icon", "golden age"],
    popularityScore: 96,
  },
  {
    fullName: "Nelson Mandela",
    slug: "nelson-mandela",
    category: "historical",
    gender: "male",
    dateOfBirth: "1918-07-18",
    nationality: "South African",
    country: "South Africa",
    city: "Johannesburg",
    occupation: "Statesman",
    biography: "Nelson Mandela fought apartheid, spent 27 years imprisoned, and became South Africa's first Black president.",
    heightCm: 180,
    eyeColor: "Brown",
    hairColor: "Gray",
    ethnicityCategory: "African",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/Nelson_Mandela_1994.jpg",
    tags: ["apartheid", "freedom", "nobel peace"],
    popularityScore: 98,
  },
  {
    fullName: "Marie Curie",
    slug: "marie-curie",
    category: "historical",
    gender: "female",
    dateOfBirth: "1867-11-07",
    nationality: "Polish-French",
    country: "France",
    city: "Paris",
    occupation: "Scientist",
    biography: "Marie Curie pioneered research on radioactivity and was the first person to win Nobel Prizes in two sciences.",
    heightCm: null,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Marie_Curie_c1920.jpg",
    tags: ["physics", "chemistry", "nobel"],
    popularityScore: 94,
  },
  {
    fullName: "Leonardo da Vinci",
    slug: "leonardo-da-vinci",
    category: "historical",
    gender: "male",
    dateOfBirth: "1452-04-15",
    nationality: "Italian",
    country: "Italy",
    city: "Florence",
    occupation: "Polymath",
    biography: "Leonardo da Vinci was a Renaissance genius whose art and inventions shaped Western civilization.",
    heightCm: null,
    eyeColor: "Brown",
    hairColor: "Brown",
    ethnicityCategory: "Caucasian",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Leonardo_da_Vinci_-_presumed_self-portrait_-_WGA12798.jpg",
    tags: ["renaissance", "art", "inventor"],
    popularityScore: 97,
  },
];

export const FUNNY_OBJECT_SEEDS = [
  { name: "Potato", slug: "potato-funny", emoji: "🥔", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Patates.jpg", tags: ["starchy", "round", "comfort"] },
  { name: "Tomato", slug: "tomato-funny", emoji: "🍅", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg", tags: ["red", "juicy", "salad"] },
  { name: "Carrot", slug: "carrot-funny", emoji: "🥕", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/CarrotDiversityLg.jpg", tags: ["orange", "crunchy", "healthy"] },
  { name: "Onion", slug: "onion-funny", emoji: "🧅", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/25/Onion_on_White.JPG", tags: ["layered", "aromatic", "kitchen"] },
  { name: "Pumpkin", slug: "pumpkin-funny", emoji: "🎃", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Fairytale_pumpkin.jpg", tags: ["autumn", "round", "festive"] },
  { name: "Banana", slug: "banana-funny", emoji: "🍌", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg", tags: ["curved", "yellow", "tropical"] },
  { name: "Broccoli", slug: "broccoli-funny", emoji: "🥦", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Broccoli_and_cross_section_edit.jpg", tags: ["green", "tree", "healthy"] },
  { name: "Eggplant", slug: "eggplant-funny", emoji: "🍆", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Aubergine.jpg", tags: ["purple", "shiny", "veggie"] },
  { name: "Panda", slug: "panda-funny", emoji: "🐼", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Grosser_Panda.JPG", tags: ["fluffy", "bamboo", "cute"] },
  { name: "Cat", slug: "cat-funny", emoji: "🐱", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Cat_November_2010-1a.jpg", tags: ["whiskers", "sassy", "meme"] },
  { name: "Koala", slug: "koala-funny", emoji: "🐨", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Koala_climbing_tree.jpg", tags: ["sleepy", "fluffy", "australia"] },
  { name: "Duck", slug: "duck-funny", emoji: "🦆", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Peeking_duck.jpg", tags: ["quack", "waddle", "pond"] },
  { name: "Owl", slug: "owl-funny", emoji: "🦉", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Great_Horned_Owl_01.jpg", tags: ["wise", "night", "staring"] },
  { name: "Sloth", slug: "sloth-funny", emoji: "🦥", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/Bradypus.jpg", tags: ["slow", "chill", "hanging"] },
  { name: "Avocado", slug: "avocado-funny", emoji: "🥑", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/Avocado_fruit.jpg", tags: ["millennial", "green", "toast"] },
  { name: "Watermelon", slug: "watermelon-funny", emoji: "🍉", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/47/Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg", tags: ["summer", "juicy", "picnic"] },
  { name: "Pineapple", slug: "pineapple-funny", emoji: "🍍", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Pineapple_and_cross_section.jpg", tags: ["tropical", "spiky", "sweet"] },
  { name: "Mushroom", slug: "mushroom-funny", emoji: "🍄", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/Fungi_in_Slovakia.jpg", tags: ["fungi", "forest", "earthy"] },
  { name: "Penguin", slug: "penguin-funny", emoji: "🐧", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/07/Emperor_Penguin_Molt.jpg", tags: ["waddle", "antarctic", "formal"] },
  { name: "Llama", slug: "llama-funny", emoji: "🦙", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Llama_on_Lake_Salinas.jpg", tags: ["fluffy", "andes", "spit"] },
];

export function hashString(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i++) {
    hash = (hash * 31 + value.charCodeAt(i)) % 2147483647;
  }
  return hash;
}

export function seededVector(seed: number, dimensions = 512): number[] {
  const vector: number[] = [];
  let state = seed;
  for (let i = 0; i < dimensions; i++) {
    state = (state * 1664525 + 1013904223) % 2147483647;
    vector.push((state / 2147483647) * 2 - 1);
  }
  const magnitude = Math.sqrt(vector.reduce((sum, value) => sum + value * value, 0));
  return vector.map((value) => value / magnitude);
}

export function seededBreakdown(seed: number): FeatureBreakdown {
  const next = (offset: number) => 70 + ((seed + offset) % 31);
  return {
    faceShape: next(1),
    eyes: next(2),
    eyebrows: next(3),
    nose: next(4),
    lips: next(5),
    smile: next(6),
    forehead: next(7),
    jawline: next(8),
    hairline: next(9),
  };
}

export function celebrityToProfile(celebrity: CelebritySeed): Profile & { storedFeatures: FeatureBreakdown } {
  const seed = hashString(celebrity.imageUrl + celebrity.slug);
  const images = [
    {
      id: `${celebrity.slug}-primary`,
      url: celebrity.imageUrl,
      alt: `${celebrity.fullName} portrait`,
      isPrimary: true,
      width: 640,
      height: 800,
    },
    ...(celebrity.extraImages ?? []).map((url, index) => ({
      id: `${celebrity.slug}-extra-${index + 1}`,
      url,
      alt: `${celebrity.fullName} photo ${index + 2}`,
      isPrimary: false,
      width: 640,
      height: 800,
    })),
  ];

  return {
    id: crypto.randomUUID(),
    slug: celebrity.slug,
    fullName: celebrity.fullName,
    gender: celebrity.gender,
    dateOfBirth: celebrity.dateOfBirth,
    nationality: celebrity.nationality,
    country: celebrity.country,
    city: celebrity.city,
    occupation: celebrity.occupation,
    biography: celebrity.biography,
    heightCm: celebrity.heightCm,
    eyeColor: celebrity.eyeColor,
    hairColor: celebrity.hairColor,
    ethnicityCategory: celebrity.ethnicityCategory,
    publicFigureCategory: celebrity.category,
    instagramUrl: celebrity.instagramUrl,
    xUrl: celebrity.xUrl,
    websiteUrl: `https://twinzy.demo/profile/${celebrity.slug}`,
    images,
    tags: celebrity.tags,
    faceEmbedding: seededVector(seed),
    popularityScore: celebrity.popularityScore,
    isFunnyObject: false,
    storedFeatures: seededBreakdown(seed),
  };
}

export function funnyObjectToProfile(
  object: (typeof FUNNY_OBJECT_SEEDS)[number],
  index: number,
): Profile & { storedFeatures: FeatureBreakdown } {
  const seed = hashString(object.imageUrl + object.slug);
  return {
    id: crypto.randomUUID(),
    slug: object.slug,
    fullName: object.name,
    gender: "other",
    dateOfBirth: "2000-01-01",
    nationality: "Everywhere",
    country: "Kitchen",
    city: "Pantry",
    occupation: `Legendary ${object.name}`,
    biography: `${object.name} ${object.emoji} is an iconic funny object admired for its instantly recognizable shape.`,
    heightCm: null,
    eyeColor: "N/A",
    hairColor: "N/A",
    ethnicityCategory: "Object",
    publicFigureCategory: "funny_object",
    images: [
      {
        id: `${object.slug}-primary`,
        url: object.imageUrl,
        alt: object.name,
        isPrimary: true,
        width: 640,
        height: 640,
      },
    ],
    tags: object.tags,
    faceEmbedding: seededVector(seed),
    popularityScore: 25 + (seed % 20),
    isFunnyObject: true,
    storedFeatures: seededBreakdown(seed),
  };
}
