appium.server.url=http://127.0.0.1:4723
appium.platformName=Android
appium.automationName=UiAutomator2
appium.deviceName=Android Emulator
appium.udid=
appium.appPackage=com.instasimulator.demo
appium.appActivity=.ui.LoginActivity
appium.app=
appium.noReset=true
