server:
  port: 8080

spring:
  application:
    name: mobile-simulator-api
  config:
    import: optional:classpath:application-simulator.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.instasimulator: INFO
