tabeeby.cors.allowed-origins[0]=${FRONTEND_PUBLIC_URL:http://localhost:3000}
tabeeby.storage.upload-dir=/app/uploads

management.endpoint.health.show-details=never

logging.level.com.tabeeby=INFO
logging.level.root=WARN
